# syntax=docker/dockerfile:experimental
FROM mpspdz:flatten

# 设置全局代理，既影响后续 RUN，也会留到最终镜像里
ENV http_proxy="http://172.18.0.1:7890" \
    https_proxy="http://172.18.0.1:7890" \
    all_proxy="http://172.18.0.1:7890" \
    no_proxy="localhost,127.0.0.1"

# 确保 SSH 服务端配置正确
RUN sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    mkdir -p /var/run/sshd

EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]
