# syntax=docker/dockerfile:experimental

FROM mpspdz:latest

# 确保 SSH 服务端配置正确
RUN sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    mkdir -p /var/run/sshd

# 设置全局代理环境变量
RUN echo 'http_proxy=http://172.20.0.1:7890' >> /etc/environment && \
    echo 'https_proxy=http://172.20.0.1:7890' >> /etc/environment && \
    echo 'all_proxy=http://172.20.0.1:7890' >> /etc/environment && \
    echo 'no_proxy=localhost,127.0.0.1' >> /etc/environment
# 暴露 SSH 端口
EXPOSE 22

# 启动 SSH 服务
CMD ["/usr/sbin/sshd", "-D"]