
FROM ubuntu:22.04

RUN apt update && apt install -y openssh-server sudo rsync python3
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN useradd -m -s /bin/bash ubuntu
RUN echo "ubuntu:test" | chpasswd && adduser ubuntu sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> \
/etc/sudoers
COPY docker_public_key.pub /home/ubuntu/.ssh/authorized_keys

# 设置代理环境变量
ENV http_proxy=http://host.docker.internal:7890
ENV https_proxy=http://host.docker.internal:7890
ENV all_proxy=http://host.docker.internal:7890
ENV no_proxy=localhost,127.0.0.1
EXPOSE 22

RUN mkdir /var/run/sshd
CMD ["/usr/sbin/sshd", "-D"]
